#!/bin/sh
set -eu

TEMPLATE_PATH="/etc/prometheus/rules/alerts.template.yml"
TARGET_PATH="/tmp/alerts.active.yml"

require_numeric() {
  value="$1"
  name="$2"
  if ! printf '%s' "$value" | grep -Eq '^[0-9]+([.][0-9]+)?$'; then
    echo "[ERROR] Invalid numeric value for ${name}: ${value}" >&2
    exit 1
  fi
}

require_duration() {
  value="$1"
  name="$2"
  if ! printf '%s' "$value" | grep -Eq '^[0-9]+[smhdw]$'; then
    echo "[ERROR] Invalid duration value for ${name}: ${value}" >&2
    exit 1
  fi
}

HTTP_ERROR_RATIO_THRESHOLD="${BIOREMPP_HTTP_ERROR_RATIO_THRESHOLD:-0.05}"
HTTP_P95_LATENCY_THRESHOLD_SECONDS="${BIOREMPP_HTTP_P95_LATENCY_SECONDS_THRESHOLD:-2}"
RESUME_ALERT_WINDOW="${BIOREMPP_RESUME_ALERT_WINDOW:-5m}"
RESUME_NOT_FOUND_THRESHOLD="${BIOREMPP_RESUME_ALERT_NOT_FOUND_THRESHOLD:-10}"
RESUME_TOKEN_MISMATCH_THRESHOLD="${BIOREMPP_RESUME_ALERT_TOKEN_MISMATCH_THRESHOLD:-5}"
RESUME_SAVE_FAILED_THRESHOLD="${BIOREMPP_RESUME_ALERT_SAVE_FAILED_THRESHOLD:-2}"
RESUME_RATE_LIMITED_THRESHOLD="${BIOREMPP_RESUME_ALERT_RATE_LIMITED_THRESHOLD:-20}"
RESUME_RATE_LIMIT_ERROR_THRESHOLD="${BIOREMPP_RESUME_ALERT_RATE_LIMIT_ERROR_THRESHOLD:-0}"
WORKERS_ACTIVE_MIN_THRESHOLD="${BIOREMPP_WORKERS_ACTIVE_MIN_THRESHOLD:-2}"
WORKER_RESTART_RATE_THRESHOLD="${BIOREMPP_WORKER_RESTART_RATE_THRESHOLD:-0.1}"
CACHE_HIT_RATIO_MIN_THRESHOLD="${BIOREMPP_CACHE_HIT_RATIO_MIN_THRESHOLD:-0.2}"

require_numeric "${HTTP_ERROR_RATIO_THRESHOLD}" "BIOREMPP_HTTP_ERROR_RATIO_THRESHOLD"
require_numeric "${HTTP_P95_LATENCY_THRESHOLD_SECONDS}" "BIOREMPP_HTTP_P95_LATENCY_SECONDS_THRESHOLD"
require_duration "${RESUME_ALERT_WINDOW}" "BIOREMPP_RESUME_ALERT_WINDOW"
require_numeric "${RESUME_NOT_FOUND_THRESHOLD}" "BIOREMPP_RESUME_ALERT_NOT_FOUND_THRESHOLD"
require_numeric "${RESUME_TOKEN_MISMATCH_THRESHOLD}" "BIOREMPP_RESUME_ALERT_TOKEN_MISMATCH_THRESHOLD"
require_numeric "${RESUME_SAVE_FAILED_THRESHOLD}" "BIOREMPP_RESUME_ALERT_SAVE_FAILED_THRESHOLD"
require_numeric "${RESUME_RATE_LIMITED_THRESHOLD}" "BIOREMPP_RESUME_ALERT_RATE_LIMITED_THRESHOLD"
require_numeric "${RESUME_RATE_LIMIT_ERROR_THRESHOLD}" "BIOREMPP_RESUME_ALERT_RATE_LIMIT_ERROR_THRESHOLD"
require_numeric "${WORKERS_ACTIVE_MIN_THRESHOLD}" "BIOREMPP_WORKERS_ACTIVE_MIN_THRESHOLD"
require_numeric "${WORKER_RESTART_RATE_THRESHOLD}" "BIOREMPP_WORKER_RESTART_RATE_THRESHOLD"
require_numeric "${CACHE_HIT_RATIO_MIN_THRESHOLD}" "BIOREMPP_CACHE_HIT_RATIO_MIN_THRESHOLD"

if [ ! -f "${TEMPLATE_PATH}" ]; then
  echo "[ERROR] Prometheus alert template not found at ${TEMPLATE_PATH}" >&2
  exit 1
fi

sed \
  -e "s/__HTTP_ERROR_RATIO_THRESHOLD__/${HTTP_ERROR_RATIO_THRESHOLD}/g" \
  -e "s/__HTTP_P95_LATENCY_THRESHOLD_SECONDS__/${HTTP_P95_LATENCY_THRESHOLD_SECONDS}/g" \
  -e "s/__RESUME_ALERT_WINDOW__/${RESUME_ALERT_WINDOW}/g" \
  -e "s/__RESUME_NOT_FOUND_THRESHOLD__/${RESUME_NOT_FOUND_THRESHOLD}/g" \
  -e "s/__RESUME_TOKEN_MISMATCH_THRESHOLD__/${RESUME_TOKEN_MISMATCH_THRESHOLD}/g" \
  -e "s/__RESUME_SAVE_FAILED_THRESHOLD__/${RESUME_SAVE_FAILED_THRESHOLD}/g" \
  -e "s/__RESUME_RATE_LIMITED_THRESHOLD__/${RESUME_RATE_LIMITED_THRESHOLD}/g" \
  -e "s/__RESUME_RATE_LIMIT_ERROR_THRESHOLD__/${RESUME_RATE_LIMIT_ERROR_THRESHOLD}/g" \
  -e "s/__WORKERS_ACTIVE_MIN_THRESHOLD__/${WORKERS_ACTIVE_MIN_THRESHOLD}/g" \
  -e "s/__WORKER_RESTART_RATE_THRESHOLD__/${WORKER_RESTART_RATE_THRESHOLD}/g" \
  -e "s/__CACHE_HIT_RATIO_MIN_THRESHOLD__/${CACHE_HIT_RATIO_MIN_THRESHOLD}/g" \
  "${TEMPLATE_PATH}" > "${TARGET_PATH}"

echo "[INFO] Rendered Prometheus alerts to ${TARGET_PATH}"

exec /bin/prometheus "$@"
